### ISSUE TITLE
all: Mach 0.3 release checklist

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#1150]
This is a tracking issue for preparing the next Mach release.

## Checklist

* [x] The blog post is ready to publish
* [x] All issues in the milestone are closed, or moved to a different milestone.
* [x] In `machengine.org` repository `static/zig` folder, `wrench script nominate-zig-index-update tag 2024.1.0-mach 0.3.0-mach` has been ran to tag the Zig version that the Mach release will use, and the [`index.json`](https://machengine.org/zig/index.json) shows the new version.
* [x] Version history at https://machengine.org/about/zig-version/ has been updated
* [x] https://github.com/hexops/mach has been tagged
* [x] https://github.com/hexops/mach-core has been tagged
* [x] The blog post has been published
* [x] #announcements has been posted
