### ISSUE TITLE
all: move Zig packages we write/maintain into the main repo

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#1165]
# Zig packages we write/maintain will move back into the main repo

Specifically, these repositories will be moved back into the main repo:

* core
* sysaudio
* sysgpu
* gamemode
* ecs
* To be decided at a later date:
  * sysjs
  * editor
  * objc-generator
  * fastfilter

The criteria for inclusion in the main repo is:

1. We think all Mach users in general will use it.
2. We believe that code is there for the long-term, we have no immediate plans to e.g. replace it.
3. It is not just a wrapper for an existing C/C++ library, it's actually a Zig implementation with code we write/maintain ourselves.

## What will definitely NOT move into the main repo?

* Bindings to C/C++ libraries
  * DirectXShaderCompiler
  * mach-gpu, mach-gpu-dawn
  * mach-model3d
  * mach-opus, mach-flac, etc.
  * mach-glfw
  * mach-freetype
  * Any "Zig bindings to an existing C/C++ library" packages, header packages, etc.

## Didn't we just break up the monorepo? Why undo that?

In 2023 we broke up our monorepo, going from 1 repository to 40+ - and instantly becoming the largest consumer of the experimental Zig package manager at the time. Partly it was inspired by:

<img width="300" alt="image" src="https://github.com/hexops/mach/assets/3173176/da09d723-bbb3-4b83-9961-95684d5e0c40">

I loved this phrasing and thought it was really funny. At the time, it kind of reaffirmed a challenge I had in the back of my mind: although Mach was very modular (modularity is our first and most important goal!) to outsiders it didn't really look very modular. We didn't have a website to communicate anything, and had tons of C/C++ bindings in our repository.

I believed that breaking up our monorepo would help with discovery, understanding the modularity of Mach, and most importantly suspected it would help us adopt the (not released at the time) package manager that we direly wanted to be an early adopter of.

However, it has caused us some challenges with specific repositories - and it also hasn't really changed perception of 'complexity' of Mach. I still see people suggest Mach is complex, and I think it is partly because we have lots of repositories and actually show how our dependencies are built rather than chucking a dll in a folder somewhere and saying 'we only depend on SDL' or something :)

We're not undoing all of this, the vast majority of the 40+ repositories we have today will remain in place. Only the ones that have Zig code we write/maintain/work on very frequently, i.e. not C/C++ bindings, will be moved back into the main repo.

## What problems does this solve?

We view the main Mach repository as a 'standard library', very similar to the Zig standard library: a bunch of code that can be largely used independently and in modular ways. Just like how you can use `std.io` without using the BigInt implementation; we see the Mach standard library as being 'use what you like.' You can see this today with e.g. how we document the ability to use [just the mach.math library if you like](https://machengine.org/engine/stdlib/)

However (my fault), since we haven't yet communicated what the engine will look like exactly and what modularity really means to us - the default assumption most people will have is that 'Mach engine' must look a lot like Unity/Unreal/Godot, a giant monolithic codebase and mythical beast that wants to eat the world. I hold a very different view of how Mach will look, but we haven't shown/communicated this yet. Moving these Zig packages we write/maintain into the Mach standard library is a first step at correcting this and showing what modularity means to us.

There are also a few specific problems this proposal will alleviate:

* If a user asks us 'Great, I'm going to use mach-core, which math library should I use?' then we tell them to use `mach.math` from our standard library. But, since we've been afraid of 'mach core depends on the engine?!' the mach-core examples today actually use a stripped down version of zmath. That's a bit crazy, we should have examples show our best guidance.
  * But the mach-core examples don't use `mach.math` today, they use a stripped-down fork of zmath, which is really weird. Why do our examples not show our best practices?
    * We did this because 'having core depend on the engine [the mythical beast]' seems scary on the surface, even though it's really not. Doing this reinforces the stereotype that our engine will be a classical monolithic engine, which is not true.
* sysgpu changes need to be tested against the mach-core examples. If one makes changes to sysgpu backends today, the best way to test them is to run the mach-core examples. We have plans to improve this, but it's true today - and having to work in two different repositories is not great.
* Working on engine examples today often involves working across many different repositories: mach-examples, mach, mach-core, mach-sysgpu, mach-ecs, etc. and it would greatly simplify contributing and testing if these lived in the same repository.

### I only want to use [core, sysgpu, sysaudio, etc], not the entire engine - does this mean I can't do that anymore?

No, you can still use just these portions if you like! The only difference is the code will now live in one repository.

The website and docs will make it very clear/explicit which parts we intend to be usable as standalone code and how to do so, that aspect doesn't change.

### If I only use e.g. sysaudio, won't this increase the download size?

Not any meaningful amount. All of this code has lived in the main repo in the past, and we are very pedantic and extremely cautious of repository size - we do not add binary assets to our history, have metrics to track repository download size, etc. and will keep it minimal.

For example, the main Mach repository is currently a 50KB tarball download through the package manager. If we compare the `--depth 1` clone and normal (full history) clone size of our repository with other popular Zig repositories, we're doing pretty well:

```
8.9M    ./mach
500K    ./mach--cloned-with-depth-1
853M    ./zig-gamedev
807M    ./zig-gamedev--cloned-with-depth-1
```

### Won't it increase compile times?

For running tests, yes - since more tests will be ran (which is a good thing!)

For consumers of any Mach package, no. Zig has lazy code evaluation, and now also has lazy dependency fetching - we will benefit from both and it will effectively be no different for you as a consumer.

### When will this happen?

I've marked this proposal as accepted, it will happen as soon as I have time to execute it.

I am open to feedback but this is one of the only ways I see to accelerate development of Zig code we write/maintain; this will substantially reduce the burden of contributing to and maintaining our Zig code and has very limited downsides - so it'd be hard to convince me this is the wrong decision.

**Comment by silversquirl** [comment]
One small suggestion regarding package size: you could store all packages in one repo, but still split them into separate tarballs for distribution.
Since the mach docs recommend downloading packages from the website already (as opposed to using github's tarball URLs) it would be easy to host separate tarballs on the website for each project.

However, the downside is that it would still require multiple `build.zig.zon` entries for people using multiple mach packages, whereas merging them all into one package with multiple modules would only need one entry.

**Comment by slimsag** [comment]
I think that's an option we can explore on a case-by-case basis if download size ever becomes a problem, yep.

**Comment by VisenDev** [comment]
I like this as I found all of mach's segments being broken up into different repos quite confusing and made it not super clear to me how things were supposed to integrate. Having the core features together makes a lot more sense imo

**Comment by slimsag** [comment]
## TODO list for closing this issue

* [ ] Move mach-ecs code into main repo
* [ ] Move mach-gamemode code into main repo
* [ ] Move mach-sysaudio code into main repo
* [ ] Move mach-sysgpu code into main repo
  * [ ] Close/merge all pending pull requests first
* [ ] Move mach-core code into main repo
  * [ ] Close/merge all pending pull requests first
* [ ] After we nominate Zig 2024.03 #1147
  * [ ] Ensure dependencies are using `lazyDependency` where possible
  * [ ] Ensure website docs have clear usage instructions showing how to _just_ use one of these packages with no extra dependencies compared to before:
    * [ ] mach-sysaudio
    * [ ] mach-sysgpu
    * [ ] mach-core

**Comment by slimsag** [comment]
All done except for https://github.com/hexops/mach/issues/1175 which will happen after we update Zig.

**Comment by Calinou** [comment]
The link on the text `here` in the README of https://github.com/hexops/mach-gamemode seems to be broken (I can't report it there as issues are disabled on that repository).

**Comment by slimsag** [comment]
@Calinou Ah! Thanks, it should be https://github.com/hexops/mach/blob/main/src/gamemode.zig - fixed.

As for the issue tracker, we try to keep all issues in the main repo https://github.com/hexops/mach/issues and just prefix them with e.g. `gamemode:` and labels to keep it all in one place so nothing is forgotten

appreciate the heads up!
