### ISSUE TITLE
Tracking issue: priorities of real-world Mach users

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#1176]
Folks using Mach to develop real-world projects will have issues affecting their projects prioritized by us.

## Current issues

- [Pixi](https://github.com/foxnne/pixi)
  - [ ] https://github.com/hexops/mach/issues/1128
  - [ ] https://github.com/hexops/mach/issues/1177
  - [ ] https://github.com/hexops/mach/issues/1184
- racer:
  - [x] https://github.com/hexops/mach/issues/1178 

To get your issue added to this list, you need to be distributing a game/app to people or show you're building something serious with it :) It also needs to be filed on GitHub with a way to reproduce it, using an up-to-date version of Mach. It doesn't need to be a minimal reproduction, however - we are willing to e.g. clone your repository and reproduce it there.

## Past issues

<details>
<summary>Past issues</summary>

- None yet!
