### ISSUE TITLE
mach: v0.2 roadmap

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#355]
The hope is to release v0.2 before end of year, or early next year. Scope may get cut, unclear yet if all of this will make it in.

In late March [we released Mach v0.1](https://devlog.hexops.com/2022/mach-v0.1-zig-graphics-in-60s/) - the story of that release was that we started work on our ECS, and got cross-platform graphics working in a super nice way.

## Timeline

Maybe end of year or the first week of new year. Scope may get cut as necessary. The way we'll do this is prepare the release blog post, and if it's exciting enough to release then we'll do that. If it's not, we'll keep working until it is :)

## What's in scope & how you can help

There are tons of issues to fix, features to add, and things to sort out :) Help is appreciated!

https://github.com/hexops/mach/milestone/2

## Blockers

- [ ] libopus (and maybe libflac) bindings
- [x] sysaudio macOS support
- [ ] `mach` CLI docs / binary releases on new website
- [x] Migrate as much as possible to the new Zig package manager
- [x] ECS query support
- [x] Integrate core/sprite2d into the ECS as an optional module ⁠gfx2d
- [ ] 2D game demo (this is TBD and we're very open to ideas/suggestions/help here in ⁠#operation-2d-game in Discord)
- [ ] Finishing touches on the new website; changelog; announcement blogpost, etc.
- [x] ECS module support

**Comment by rofrol** [comment]
Why was it closed?

**Comment by slimsag** [comment]
It has moved here: https://github.com/hexops/mach/milestone/2
