### ISSUE TITLE
sysaudio: rewrite (drop libsoundio dependency)

### ISSUE THREAD

**Issue by alichraghi** [hexops/mach#625]
## Motivation
- more Zig:zap:
- AAudio/Web (and more) backends
- catch bugs
- easily add/drop features

## TODO
- [X] Pulseaudio backend
- [X] Alsa (*unix*) backend
- [X] Dummy backend
- [x] Jack backend
- [x] WASAPI/Asio (*Windows*) backend
- [X] #484
- [ ] CoreAudio (*Apple*) backend
- [ ] AAudio backend (*Android*)
- [ ] Web backend

Currently progress can be followed in [alichraghi/libsoundio](https://github.com/alichraghi/libsoundio)

**Comment by slimsag** [comment]
Very exciting :) Do you think we could easily shell out to the C implementation of libsoundio to merge this work more quickly?

e.g. use the new Zig backend for pulseaudio/alsa right now, and shell out to libsoundio for the others? Or would that be more work

**Comment by alichraghi** [comment]
Hmm, not too hard but it's changing so fast and both PulseAudio and Alsa backends still has known bugs (and more features :P ). i think i'll find it stable enough after implementing WASAPI
