### ISSUE TITLE
gpu-dawn: x86_64-windows support

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#86]
- [ ] https://github.com/hexops/mach/issues/167
- [x] Publish binary releases of `gpu-dawn` for Windows
- [x] #169
- [x] Build DirectXShaderCompiler with `zig build` system
- [x] Land patches to `gpu-dawn/build.zig` required for Windows builds
- [x] Update and publish WIDL-produced Direct3D headers in a Windows SDK repo
- [x] Add Windows SDK repo to `system_sdk.zig` for use in `mach/gpu-dawn`
- [x] Merge patches to Dawn into `main` of our fork,
  - [x] https://github.com/hexops/dawn/pull/8
  - [x] https://github.com/hexops/dawn/pull/7
  - [x] https://github.com/hexops/dawn/pull/6
- [x] Patch Dawn to eliminate dependency on `windows.ui.*` headers and fix other issues building with Zig
  - [x] https://github.com/hexops/dawn/pull/8
  - [x] https://github.com/hexops/dawn/pull/7
  - [x] https://github.com/hexops/dawn/pull/6
- [x] Debug the compatibility issues with DX debug API expecting 3 params in Dawn vs. 1 according to headers (???) -> most likely due to outdated d3d12 headers.
- [x] Debug cause of segfaults that occurred when hacking in updated d3d headers (see COM calling convention issues discussed at https://github.com/ziglang/zig/issues/9998#issuecomment-997088467)
- [x] Produce up-to-date MinGW/GNU compatible Direct3D headers https://github.com/ziglang/zig/issues/9998#issuecomment-997088467

**Comment by slimsag** [comment]
Super close to having Windows builds actually. Everything compiles, but need dxcompiler to get it to link and then we should be golden. Lots of changes to land here both in Mach and upstream in Dawn itself, though:

- [x] Debug cause of segfaults that occurred when hacking in updated d3d headers (see COM calling convention issues discussed at https://github.com/ziglang/zig/issues/9998#issuecomment-997088467)
- [x] Produce up-to-date MinGW/GNU compatible Direct3D headers https://github.com/ziglang/zig/issues/9998#issuecomment-997088467
- [ ] Build DirectXShaderCompiler with Zig (i.e. for default `x86_64-windows-gnu` target, with msvc it's available prebuilt)
- [ ] Send changes to `mach/gpu-dawn`s `build_dawn.zig` required for Windows builds
- [ ] Send CL to Dawn to add `#define` that disables UWP-free builds
- [ ] Publish WIDL-produced Direct3D headers in a Windows SDK repo, use them in `mach/gpu-dawn`
- [ ] Debug the compatibility issues with DX debug API expecting 3 params in Dawn vs. 1 according to headers (???)

**Comment by slimsag** [comment]
This officially works, complete with binary releases from the CI system and cross compilation from any OS:

```
cd gpu-dawn/
zig build run-dawn-example -Dtarget=x86_64-windows-gnu
```

If you want to build from source, just add `-Ddawn-from-source=true` but note that you'll need a patched version of Zig temporarily until the patch lands upstream, see https://github.com/hexops/mach/issues/167

No `-msvc` builds, yet.

**Comment by alichraghi** [comment]
congrats
