### ISSUE TITLE
v0.2 release final checklist

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#923]
- [x] Make it clear on website what Mach can/can't be used for today
- [x] `!wrench schedule-now update-deps` produces no PRs and all dependencies are up-to-date
- [x] https://wrench.machengine.org/projects/ reports all CI is green
- [x] New website is released
- [x] Wrench reports no broken URLs
- [x] v0.2 has been tagged in:
  - [x] https://github.com/hexops/mach
  - [x] https://github.com/hexops/mach-examples
  - [x] https://github.com/hexops/mach-core
  - [x] https://github.com/hexops/machengine.org
- [x] Announcement blog post is published
- [x] Website is updated with `alert` in config.toml and homepage link to "What's new in v0.2?"
