### ISSUE TITLE
glfw: tracking issue for ensuring upstream patches land

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#95]
- [ ] do not rely on undefined behavior in glfwSetWindowIcon for X11 https://github.com/glfw/glfw/pull/1986
- [ ] update docstring which inaccurately says GLFW_CONTEXT_REVISION is a window hint https://github.com/glfw/glfw/pull/1992
- [ ] Fix undefined behaviour in X11 keypress handling https://github.com/glfw/glfw/pull/1989
- [ ] Add possible error comment https://github.com/glfw/glfw/pull/1998
- [ ] https://github.com/hexops/mach/commit/7d47233d7a5a97241ad16a148c153831ce5d555d
  - https://github.com/ziglang/zig/pull/10202
  - https://github.com/ziglang/fetch-them-macos-headers/pull/15

**Comment by InKryption** [comment]
Should add https://github.com/glfw/glfw/pull/2007

**Comment by slimsag** [comment]
@iddev5 @AliChraghi FYI, my general thought process is that:

1. It's unlikely there will be more patches like these to glfw/glfw, possibly patches to improve comments/docs/etc but probably not critical things we need to patch in our vendored copy of GLFW.
2. My general rule of thumb is that we use the upstream version in all cases, except if there is a bug caused by using our Zig compilation method.
    * OK: we patch undefined behavior in our vendored copy (with a PR sent upstream which is being tracked to ensure we do in fact land it upstream), because our behavior with Zig (which has ubsan on by default) would differ from the normal experience of someone using GLFW with e.g. a C compiler.
    * Not OK: we patch our vendored copy to fix Wayland bugs, for example. We would instead need to wait for those to be officially fixed upstream by sending a PR and waiting for a released version, and only then we can adopt them here in `main`.
3. Any new patches to our vendored copy from here on out should require a proper `.patch` file applied as part of `update-upstream.sh`, to prevent issues like #149

**Comment by iddev5** [comment]
I agree. Such patches should only make minor but critical changes i.e things like comment or misinformation or doc patches doesnt seems important. And at the same time should not add new feature or make difference from glfw (as was your 2.b point :))

**Comment by alichraghi** [comment]
seems fixed
https://github.com/glfw/glfw/pull/1989#issuecomment-1065086444

**Comment by slimsag** [comment]
Looks like we can use upstream now, closing.
